language: node_js

node_js:
  - '6'

before_install:
  - openssl aes-256-cbc -K $encrypted_830d3b21a25d_key -iv $encrypted_830d3b21a25d_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 192.168.33.10\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - npm run test

after_success:
  - tar -cvf nodeJS.tar *    # 打包并压缩代码
  - scp nodeJS.tar vagrant@192.168.33.10:~/nodetest/  # 复制代码到生产服务器上
  - ssh vagrant@192.168.33.10 'tar -xvf nodeJS.tar'   # 解压
  - ssh vagrant@192.168.33.10 'cd ~/nodetest && nohup node ~/nodetest/nodeJS/index.js &'  # 重启
